apiVersion: cert-manager.io/v1aplha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https:/acme-v02.api.letsencrypt.org/directory
    email: "youremail@email.com"
    privateSecretKeyRef:
      name: letsencrypt-prod
    solvers:
      - http01:
        ingress:
          class: nginx
