apiVersion: skaffold/v2alpha2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: aldam1r/fib-client
      context: ./client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "./src/*.css"
            dest: "/app/src/"
          - src: "src/*.js"
            dest: "/app/src/"
          - src: "src/*.html"
            dest: "/app/src/"
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml                        